// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4oG-r1bWV35oXMrbEk-R0bBqAkyg9iJI',
    appId: '1:523555491831:web:a59456c7a3dd5cd13968f2',
    messagingSenderId: '523555491831',
    projectId: 'europroyecto-4ccae',
    authDomain: 'europroyecto-4ccae.firebaseapp.com',
    databaseURL: 'https://europroyecto-4ccae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'europroyecto-4ccae.appspot.com',
    measurementId: 'G-D3QECR63VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsr9N0TRmZS35PsouiKun__37s6Q__L38',
    appId: '1:523555491831:android:ec231dd4d2f94df93968f2',
    messagingSenderId: '523555491831',
    projectId: 'europroyecto-4ccae',
    databaseURL: 'https://europroyecto-4ccae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'europroyecto-4ccae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALDBhpTx1Ouwoz53oP7tP9XI-opghLlUA',
    appId: '1:523555491831:ios:b8b63b87124fa8ab3968f2',
    messagingSenderId: '523555491831',
    projectId: 'europroyecto-4ccae',
    databaseURL: 'https://europroyecto-4ccae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'europroyecto-4ccae.appspot.com',
    iosClientId: '523555491831-lsmf2tu40qsiqrr01njldqh3mvl8k3ta.apps.googleusercontent.com',
    iosBundleId: 'com.europroyectos.jj.europroyectosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALDBhpTx1Ouwoz53oP7tP9XI-opghLlUA',
    appId: '1:523555491831:ios:8ff15ffadc8b727c3968f2',
    messagingSenderId: '523555491831',
    projectId: 'europroyecto-4ccae',
    databaseURL: 'https://europroyecto-4ccae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'europroyecto-4ccae.appspot.com',
    iosClientId: '523555491831-0ih9o9llv2s4rs92c0bjmun30v8cbhre.apps.googleusercontent.com',
    iosBundleId: 'com.europroyectos.jj.europroyectosApp.RunnerTests',
  );
}
